###############################################################################
# keycloak-bootstrap-admin — Inputs
#
# Cloud-agnostic. Caller supplies the realm name, role name, and admin user
# identity. Module outputs stable secrets and ready-to-merge realm JSON
# snippets. Caller wires those outputs into their secret backend (Secrets
# Manager, Vault, native K8s Secrets, etc.) and into their realm import
# pipeline (e.g. keycloakConfigCli via the aws-eks-keycloak module).
###############################################################################

variable "realm_name" {
  description = "Keycloak realm name the bootstrap client and admin user are scoped to. The bootstrap client is created INSIDE this realm; it cannot manage other realms or the master realm. Must be a valid Keycloak realm name."
  type        = string

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9_-]*$", var.realm_name))
    error_message = "realm_name must start with a letter and contain only alphanumerics, hyphens, or underscores."
  }
}

variable "bootstrap_client_id" {
  description = "Keycloak clientId for the bootstrap service-account client. Must be a DNS-label-style identifier. Default 'platform-bootstrap' is descriptive without being product-specific. Override per deployment if you maintain multiple realms with the same module."
  type        = string
  default     = "platform-bootstrap"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]*$", var.bootstrap_client_id)) && length(var.bootstrap_client_id) <= 64
    error_message = "bootstrap_client_id must be a lowercase DNS-label (alphanumerics + hyphens, max 64 chars)."
  }
}

variable "bootstrap_client_name" {
  description = "Human-readable name shown in the Keycloak admin UI for the bootstrap client. Useful for auditors. Optional — defaults to a generic descriptor."
  type        = string
  default     = "Platform Bootstrap (one-shot admin user provisioning)"
}

variable "admin_user_email" {
  description = "Email address for the admin user that will be provisioned at first apply. Used as both Keycloak login (when 'Login with email' is enabled) and the destination for the password-setup email Keycloak sends via executeActionsEmail. MUST be a real, monitored mailbox in production."
  type        = string

  validation {
    condition     = can(regex("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", var.admin_user_email))
    error_message = "admin_user_email must be a valid email address (e.g. ops@example.com)."
  }
}

variable "admin_user_firstname" {
  description = "First name for the admin user, written into the Keycloak user record. Required by Keycloak's user schema; surfaces in audit events and the admin UI."
  type        = string

  validation {
    condition     = length(trimspace(var.admin_user_firstname)) > 0 && can(regex("^[^\n\r=\"']+$", var.admin_user_firstname))
    error_message = "admin_user_firstname must be non-empty and must not contain newlines, '=', or quote characters (would corrupt .env rendering and JSON splicing)."
  }
}

variable "admin_user_lastname" {
  description = "Last name for the admin user, written into the Keycloak user record. Required by Keycloak's user schema; surfaces in audit events and the admin UI."
  type        = string

  validation {
    condition     = length(trimspace(var.admin_user_lastname)) > 0 && can(regex("^[^\n\r=\"']+$", var.admin_user_lastname))
    error_message = "admin_user_lastname must be non-empty and must not contain newlines, '=', or quote characters (would corrupt .env rendering and JSON splicing)."
  }
}

variable "admin_user_role" {
  description = "Realm role assigned to the admin user at provisioning time. Caller-supplied because role hierarchies vary by deployment (some realms use 'admin', others 'platform-owner', 'super-admin', etc.). The role MUST already exist in the realm — define it in your realm JSON or via terraform-provider-keycloak."
  type        = string

  validation {
    condition     = length(trimspace(var.admin_user_role)) > 0 && can(regex("^[A-Za-z][A-Za-z0-9_.-]*$", var.admin_user_role))
    error_message = "admin_user_role must be non-empty, start with a letter, and contain only letters, digits, underscores, periods, or hyphens (matches Keycloak realm-role naming)."
  }
}

variable "bootstrap_client_secret_length" {
  description = "Length in characters of the generated bootstrap client secret. The default of 48 is sufficient for >256 bits of entropy at the alphanumeric alphabet generated by random_password (special=false)."
  type        = number
  default     = 48

  validation {
    condition     = var.bootstrap_client_secret_length >= 32 && var.bootstrap_client_secret_length <= 128
    error_message = "bootstrap_client_secret_length must be between 32 and 128 characters."
  }
}

variable "admin_user_required_actions" {
  description = "Initial requiredActions assigned to the admin user at creation. These force the user to complete the listed actions before they can authenticate normally. The default ['UPDATE_PASSWORD','VERIFY_EMAIL'] mirrors the recommended onboarding ceremony for least-privilege admin users — Keycloak emails the user a one-time link via executeActionsEmail and only the user (not the operator) sees the chosen password."
  type        = list(string)
  default     = ["UPDATE_PASSWORD", "VERIFY_EMAIL"]

  validation {
    condition     = alltrue([for a in var.admin_user_required_actions : can(regex("^[A-Z][A-Z0-9_]*$", a))])
    error_message = "admin_user_required_actions entries must match Keycloak's action-key shape: uppercase letters, digits, and underscores, starting with a letter (e.g. UPDATE_PASSWORD, VERIFY_EMAIL, CONFIGURE_TOTP)."
  }
}
